apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 15s

  - name: InfluxDB_JMeter
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: benchmark
      defaultBucket: jmeter
      tlsSkipVerify: true
    secureJsonData:
      token: my-super-secret-token
    editable: true

